// Code generated by protoc-gen-go. DO NOT EDIT.
// source: newbee.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PT int32

const (
	PT_UNKNOWN          PT = 0
	PT_HEARTBEAT        PT = 900001
	PT_JOIN_ROOM        PT = 900002
	PT_LOADING_PROGRESS PT = 900003
	PT_GAME_READY       PT = 900004
	PT_GAME_FRAME       PT = 900005
)

var PT_name = map[int32]string{
	0:      "UNKNOWN",
	900001: "HEARTBEAT",
	900002: "JOIN_ROOM",
	900003: "LOADING_PROGRESS",
	900004: "GAME_READY",
	900005: "GAME_FRAME",
}

var PT_value = map[string]int32{
	"UNKNOWN":          0,
	"HEARTBEAT":        900001,
	"JOIN_ROOM":        900002,
	"LOADING_PROGRESS": 900003,
	"GAME_READY":       900004,
	"GAME_FRAME":       900005,
}

func (x PT) String() string {
	return proto.EnumName(PT_name, int32(x))
}

func (PT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{0}
}

type JOIN_ROOM_CODE int32

const (
	JOIN_ROOM_CODE_SUCCESS          JOIN_ROOM_CODE = 0
	JOIN_ROOM_CODE_ROOM_NOT_EXIST   JOIN_ROOM_CODE = 1
	JOIN_ROOM_CODE_PLAYER_NOT_EXIST JOIN_ROOM_CODE = 2
	JOIN_ROOM_CODE_TOKEN_NOT_EXIST  JOIN_ROOM_CODE = 3
)

var JOIN_ROOM_CODE_name = map[int32]string{
	0: "SUCCESS",
	1: "ROOM_NOT_EXIST",
	2: "PLAYER_NOT_EXIST",
	3: "TOKEN_NOT_EXIST",
}

var JOIN_ROOM_CODE_value = map[string]int32{
	"SUCCESS":          0,
	"ROOM_NOT_EXIST":   1,
	"PLAYER_NOT_EXIST": 2,
	"TOKEN_NOT_EXIST":  3,
}

func (x JOIN_ROOM_CODE) String() string {
	return proto.EnumName(JOIN_ROOM_CODE_name, int32(x))
}

func (JOIN_ROOM_CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{1}
}

// --------------------------------------------------------------------------------
// 客户端 - 心跳请求参数
type C2SHeartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SHeartbeat) Reset()         { *m = C2SHeartbeat{} }
func (m *C2SHeartbeat) String() string { return proto.CompactTextString(m) }
func (*C2SHeartbeat) ProtoMessage()    {}
func (*C2SHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{0}
}

func (m *C2SHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SHeartbeat.Unmarshal(m, b)
}
func (m *C2SHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SHeartbeat.Marshal(b, m, deterministic)
}
func (m *C2SHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SHeartbeat.Merge(m, src)
}
func (m *C2SHeartbeat) XXX_Size() int {
	return xxx_messageInfo_C2SHeartbeat.Size(m)
}
func (m *C2SHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_C2SHeartbeat proto.InternalMessageInfo

// 服务器端 - 心跳返回结果
type S2CHeartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CHeartbeat) Reset()         { *m = S2CHeartbeat{} }
func (m *S2CHeartbeat) String() string { return proto.CompactTextString(m) }
func (*S2CHeartbeat) ProtoMessage()    {}
func (*S2CHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{1}
}

func (m *S2CHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHeartbeat.Unmarshal(m, b)
}
func (m *S2CHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHeartbeat.Marshal(b, m, deterministic)
}
func (m *S2CHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHeartbeat.Merge(m, src)
}
func (m *S2CHeartbeat) XXX_Size() int {
	return xxx_messageInfo_S2CHeartbeat.Size(m)
}
func (m *S2CHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHeartbeat proto.InternalMessageInfo

// --------------------------------------------------------------------------------
// 客户端 - 加入房间请求参数
type C2SJoinRoom struct {
	RoomId               uint64   `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerId             uint64   `protobuf:"varint,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SJoinRoom) Reset()         { *m = C2SJoinRoom{} }
func (m *C2SJoinRoom) String() string { return proto.CompactTextString(m) }
func (*C2SJoinRoom) ProtoMessage()    {}
func (*C2SJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{2}
}

func (m *C2SJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SJoinRoom.Unmarshal(m, b)
}
func (m *C2SJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SJoinRoom.Marshal(b, m, deterministic)
}
func (m *C2SJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SJoinRoom.Merge(m, src)
}
func (m *C2SJoinRoom) XXX_Size() int {
	return xxx_messageInfo_C2SJoinRoom.Size(m)
}
func (m *C2SJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_C2SJoinRoom proto.InternalMessageInfo

func (m *C2SJoinRoom) GetRoomId() uint64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *C2SJoinRoom) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *C2SJoinRoom) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 服务器端 - 加入房间返回结果
type S2CJoinRoom struct {
	Code                 JOIN_ROOM_CODE `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.JOIN_ROOM_CODE" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CJoinRoom) Reset()         { *m = S2CJoinRoom{} }
func (m *S2CJoinRoom) String() string { return proto.CompactTextString(m) }
func (*S2CJoinRoom) ProtoMessage()    {}
func (*S2CJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{3}
}

func (m *S2CJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CJoinRoom.Unmarshal(m, b)
}
func (m *S2CJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CJoinRoom.Marshal(b, m, deterministic)
}
func (m *S2CJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CJoinRoom.Merge(m, src)
}
func (m *S2CJoinRoom) XXX_Size() int {
	return xxx_messageInfo_S2CJoinRoom.Size(m)
}
func (m *S2CJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_S2CJoinRoom proto.InternalMessageInfo

func (m *S2CJoinRoom) GetCode() JOIN_ROOM_CODE {
	if m != nil {
		return m.Code
	}
	return JOIN_ROOM_CODE_SUCCESS
}

// 客户端 - 载入游戏进度请求参数
type C2SLoadingProgress struct {
	Progress             int32    `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SLoadingProgress) Reset()         { *m = C2SLoadingProgress{} }
func (m *C2SLoadingProgress) String() string { return proto.CompactTextString(m) }
func (*C2SLoadingProgress) ProtoMessage()    {}
func (*C2SLoadingProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{4}
}

func (m *C2SLoadingProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SLoadingProgress.Unmarshal(m, b)
}
func (m *C2SLoadingProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SLoadingProgress.Marshal(b, m, deterministic)
}
func (m *C2SLoadingProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SLoadingProgress.Merge(m, src)
}
func (m *C2SLoadingProgress) XXX_Size() int {
	return xxx_messageInfo_C2SLoadingProgress.Size(m)
}
func (m *C2SLoadingProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SLoadingProgress.DiscardUnknown(m)
}

var xxx_messageInfo_C2SLoadingProgress proto.InternalMessageInfo

func (m *C2SLoadingProgress) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

// 服务器端 - 载入游戏进度返回结果，服务器端每收到 LOADING_PROGRESS 消息之后，都会向所有的客户端广播所有用户当前最新的加载进度
type S2CLoadingProgress struct {
	Infos                []*LoadingProgressInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *S2CLoadingProgress) Reset()         { *m = S2CLoadingProgress{} }
func (m *S2CLoadingProgress) String() string { return proto.CompactTextString(m) }
func (*S2CLoadingProgress) ProtoMessage()    {}
func (*S2CLoadingProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{5}
}

func (m *S2CLoadingProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CLoadingProgress.Unmarshal(m, b)
}
func (m *S2CLoadingProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CLoadingProgress.Marshal(b, m, deterministic)
}
func (m *S2CLoadingProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CLoadingProgress.Merge(m, src)
}
func (m *S2CLoadingProgress) XXX_Size() int {
	return xxx_messageInfo_S2CLoadingProgress.Size(m)
}
func (m *S2CLoadingProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CLoadingProgress.DiscardUnknown(m)
}

var xxx_messageInfo_S2CLoadingProgress proto.InternalMessageInfo

func (m *S2CLoadingProgress) GetInfos() []*LoadingProgressInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type LoadingProgressInfo struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Progress             int32    `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadingProgressInfo) Reset()         { *m = LoadingProgressInfo{} }
func (m *LoadingProgressInfo) String() string { return proto.CompactTextString(m) }
func (*LoadingProgressInfo) ProtoMessage()    {}
func (*LoadingProgressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{6}
}

func (m *LoadingProgressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadingProgressInfo.Unmarshal(m, b)
}
func (m *LoadingProgressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadingProgressInfo.Marshal(b, m, deterministic)
}
func (m *LoadingProgressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadingProgressInfo.Merge(m, src)
}
func (m *LoadingProgressInfo) XXX_Size() int {
	return xxx_messageInfo_LoadingProgressInfo.Size(m)
}
func (m *LoadingProgressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadingProgressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoadingProgressInfo proto.InternalMessageInfo

func (m *LoadingProgressInfo) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *LoadingProgressInfo) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

// --------------------------------------------------------------------------------
// 客户端 - 游戏加载完成，可以开始游戏
type C2SGameReady struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGameReady) Reset()         { *m = C2SGameReady{} }
func (m *C2SGameReady) String() string { return proto.CompactTextString(m) }
func (*C2SGameReady) ProtoMessage()    {}
func (*C2SGameReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{7}
}

func (m *C2SGameReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGameReady.Unmarshal(m, b)
}
func (m *C2SGameReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGameReady.Marshal(b, m, deterministic)
}
func (m *C2SGameReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGameReady.Merge(m, src)
}
func (m *C2SGameReady) XXX_Size() int {
	return xxx_messageInfo_C2SGameReady.Size(m)
}
func (m *C2SGameReady) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGameReady.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGameReady proto.InternalMessageInfo

// 服务器端 - 收到所有客户端加载完成消息之后，将向所有客户端广播此消息
type S2CGameReady struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CGameReady) Reset()         { *m = S2CGameReady{} }
func (m *S2CGameReady) String() string { return proto.CompactTextString(m) }
func (*S2CGameReady) ProtoMessage()    {}
func (*S2CGameReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{8}
}

func (m *S2CGameReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGameReady.Unmarshal(m, b)
}
func (m *S2CGameReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGameReady.Marshal(b, m, deterministic)
}
func (m *S2CGameReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGameReady.Merge(m, src)
}
func (m *S2CGameReady) XXX_Size() int {
	return xxx_messageInfo_S2CGameReady.Size(m)
}
func (m *S2CGameReady) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGameReady.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGameReady proto.InternalMessageInfo

// --------------------------------------------------------------------------------
// 客户端 - 游戏帧请求参数
type C2SGameFrame struct {
	FrameId              uint64       `protobuf:"varint,1,opt,name=FrameId,proto3" json:"FrameId,omitempty"`
	PlayerMove           *PlayerMove  `protobuf:"bytes,2,opt,name=playerMove,proto3" json:"playerMove,omitempty"`
	PlayerSkill          *PlayerSkill `protobuf:"bytes,3,opt,name=playerSkill,proto3" json:"playerSkill,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *C2SGameFrame) Reset()         { *m = C2SGameFrame{} }
func (m *C2SGameFrame) String() string { return proto.CompactTextString(m) }
func (*C2SGameFrame) ProtoMessage()    {}
func (*C2SGameFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{9}
}

func (m *C2SGameFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGameFrame.Unmarshal(m, b)
}
func (m *C2SGameFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGameFrame.Marshal(b, m, deterministic)
}
func (m *C2SGameFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGameFrame.Merge(m, src)
}
func (m *C2SGameFrame) XXX_Size() int {
	return xxx_messageInfo_C2SGameFrame.Size(m)
}
func (m *C2SGameFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGameFrame.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGameFrame proto.InternalMessageInfo

func (m *C2SGameFrame) GetFrameId() uint64 {
	if m != nil {
		return m.FrameId
	}
	return 0
}

func (m *C2SGameFrame) GetPlayerMove() *PlayerMove {
	if m != nil {
		return m.PlayerMove
	}
	return nil
}

func (m *C2SGameFrame) GetPlayerSkill() *PlayerSkill {
	if m != nil {
		return m.PlayerSkill
	}
	return nil
}

type PlayerMove struct {
	X                    uint32   `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerMove) Reset()         { *m = PlayerMove{} }
func (m *PlayerMove) String() string { return proto.CompactTextString(m) }
func (*PlayerMove) ProtoMessage()    {}
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{10}
}

func (m *PlayerMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMove.Unmarshal(m, b)
}
func (m *PlayerMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMove.Marshal(b, m, deterministic)
}
func (m *PlayerMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMove.Merge(m, src)
}
func (m *PlayerMove) XXX_Size() int {
	return xxx_messageInfo_PlayerMove.Size(m)
}
func (m *PlayerMove) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMove.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMove proto.InternalMessageInfo

func (m *PlayerMove) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PlayerMove) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PlayerSkill struct {
	SkillId              uint32   `protobuf:"varint,1,opt,name=SkillId,proto3" json:"SkillId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerSkill) Reset()         { *m = PlayerSkill{} }
func (m *PlayerSkill) String() string { return proto.CompactTextString(m) }
func (*PlayerSkill) ProtoMessage()    {}
func (*PlayerSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{11}
}

func (m *PlayerSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSkill.Unmarshal(m, b)
}
func (m *PlayerSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSkill.Marshal(b, m, deterministic)
}
func (m *PlayerSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSkill.Merge(m, src)
}
func (m *PlayerSkill) XXX_Size() int {
	return xxx_messageInfo_PlayerSkill.Size(m)
}
func (m *PlayerSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSkill.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSkill proto.InternalMessageInfo

func (m *PlayerSkill) GetSkillId() uint32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

// 服务器端 - 游戏返回帧数据
type S2CGameFrame struct {
	Frames               []*GameFrame `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *S2CGameFrame) Reset()         { *m = S2CGameFrame{} }
func (m *S2CGameFrame) String() string { return proto.CompactTextString(m) }
func (*S2CGameFrame) ProtoMessage()    {}
func (*S2CGameFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{12}
}

func (m *S2CGameFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGameFrame.Unmarshal(m, b)
}
func (m *S2CGameFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGameFrame.Marshal(b, m, deterministic)
}
func (m *S2CGameFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGameFrame.Merge(m, src)
}
func (m *S2CGameFrame) XXX_Size() int {
	return xxx_messageInfo_S2CGameFrame.Size(m)
}
func (m *S2CGameFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGameFrame.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGameFrame proto.InternalMessageInfo

func (m *S2CGameFrame) GetFrames() []*GameFrame {
	if m != nil {
		return m.Frames
	}
	return nil
}

type GameFrame struct {
	FrameId              uint64          `protobuf:"varint,1,opt,name=frameId,proto3" json:"frameId,omitempty"`
	Commands             []*FrameCommand `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameFrame) Reset()         { *m = GameFrame{} }
func (m *GameFrame) String() string { return proto.CompactTextString(m) }
func (*GameFrame) ProtoMessage()    {}
func (*GameFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{13}
}

func (m *GameFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameFrame.Unmarshal(m, b)
}
func (m *GameFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameFrame.Marshal(b, m, deterministic)
}
func (m *GameFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameFrame.Merge(m, src)
}
func (m *GameFrame) XXX_Size() int {
	return xxx_messageInfo_GameFrame.Size(m)
}
func (m *GameFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_GameFrame.DiscardUnknown(m)
}

var xxx_messageInfo_GameFrame proto.InternalMessageInfo

func (m *GameFrame) GetFrameId() uint64 {
	if m != nil {
		return m.FrameId
	}
	return 0
}

func (m *GameFrame) GetCommands() []*FrameCommand {
	if m != nil {
		return m.Commands
	}
	return nil
}

type FrameCommand struct {
	PlayerId             uint64       `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerMove           *PlayerMove  `protobuf:"bytes,2,opt,name=playerMove,proto3" json:"playerMove,omitempty"`
	PlayerSkill          *PlayerSkill `protobuf:"bytes,3,opt,name=playerSkill,proto3" json:"playerSkill,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FrameCommand) Reset()         { *m = FrameCommand{} }
func (m *FrameCommand) String() string { return proto.CompactTextString(m) }
func (*FrameCommand) ProtoMessage()    {}
func (*FrameCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{14}
}

func (m *FrameCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameCommand.Unmarshal(m, b)
}
func (m *FrameCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameCommand.Marshal(b, m, deterministic)
}
func (m *FrameCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameCommand.Merge(m, src)
}
func (m *FrameCommand) XXX_Size() int {
	return xxx_messageInfo_FrameCommand.Size(m)
}
func (m *FrameCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameCommand.DiscardUnknown(m)
}

var xxx_messageInfo_FrameCommand proto.InternalMessageInfo

func (m *FrameCommand) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *FrameCommand) GetPlayerMove() *PlayerMove {
	if m != nil {
		return m.PlayerMove
	}
	return nil
}

func (m *FrameCommand) GetPlayerSkill() *PlayerSkill {
	if m != nil {
		return m.PlayerSkill
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.PT", PT_name, PT_value)
	proto.RegisterEnum("protocol.JOIN_ROOM_CODE", JOIN_ROOM_CODE_name, JOIN_ROOM_CODE_value)
	proto.RegisterType((*C2SHeartbeat)(nil), "protocol.C2SHeartbeat")
	proto.RegisterType((*S2CHeartbeat)(nil), "protocol.S2CHeartbeat")
	proto.RegisterType((*C2SJoinRoom)(nil), "protocol.C2SJoinRoom")
	proto.RegisterType((*S2CJoinRoom)(nil), "protocol.S2CJoinRoom")
	proto.RegisterType((*C2SLoadingProgress)(nil), "protocol.C2SLoadingProgress")
	proto.RegisterType((*S2CLoadingProgress)(nil), "protocol.S2CLoadingProgress")
	proto.RegisterType((*LoadingProgressInfo)(nil), "protocol.LoadingProgressInfo")
	proto.RegisterType((*C2SGameReady)(nil), "protocol.C2SGameReady")
	proto.RegisterType((*S2CGameReady)(nil), "protocol.S2CGameReady")
	proto.RegisterType((*C2SGameFrame)(nil), "protocol.C2SGameFrame")
	proto.RegisterType((*PlayerMove)(nil), "protocol.PlayerMove")
	proto.RegisterType((*PlayerSkill)(nil), "protocol.PlayerSkill")
	proto.RegisterType((*S2CGameFrame)(nil), "protocol.S2CGameFrame")
	proto.RegisterType((*GameFrame)(nil), "protocol.GameFrame")
	proto.RegisterType((*FrameCommand)(nil), "protocol.FrameCommand")
}

func init() { proto.RegisterFile("newbee.proto", fileDescriptor_e7594dbd1bcb6139) }

var fileDescriptor_e7594dbd1bcb6139 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xdf, 0x6b, 0xda, 0x50,
	0x14, 0x6e, 0xb4, 0x5a, 0x3d, 0x51, 0x1b, 0xae, 0x4e, 0xc2, 0x60, 0x20, 0x79, 0x99, 0x74, 0x43,
	0x46, 0x3a, 0xdc, 0x43, 0x9f, 0xb2, 0x98, 0xda, 0xb4, 0x9a, 0xc8, 0x4d, 0x4a, 0x27, 0x0c, 0x24,
	0x9a, 0x6b, 0x91, 0x9a, 0xdc, 0x12, 0x65, 0xab, 0x7f, 0xc9, 0xd8, 0xe3, 0x7e, 0xfd, 0x8d, 0xbe,
	0x8e, 0xdc, 0xc4, 0x24, 0xca, 0xe8, 0xe3, 0x9e, 0x72, 0xbe, 0x73, 0xbe, 0x7b, 0xce, 0x77, 0xce,
	0x47, 0xa0, 0xe2, 0x93, 0xaf, 0x53, 0x42, 0x3a, 0x8f, 0x01, 0x5d, 0x53, 0x54, 0x62, 0x9f, 0x19,
	0x5d, 0x4a, 0x35, 0xa8, 0xa8, 0xb2, 0x75, 0x45, 0x9c, 0x60, 0x3d, 0x25, 0xce, 0x3a, 0xc4, 0x96,
	0xac, 0xa6, 0xf8, 0x0e, 0x78, 0x55, 0xb6, 0xae, 0xe9, 0xc2, 0xc7, 0x94, 0x7a, 0xa8, 0x09, 0xc5,
	0x80, 0x52, 0x4f, 0x77, 0x45, 0xae, 0xc5, 0xb5, 0x8f, 0x71, 0x8c, 0xd0, 0x4b, 0x28, 0x3d, 0x2e,
	0x9d, 0x0d, 0x09, 0x74, 0x57, 0xcc, 0xb1, 0x4a, 0x82, 0x51, 0x03, 0x0a, 0x6b, 0xfa, 0x40, 0x7c,
	0x31, 0xdf, 0xe2, 0xda, 0x65, 0x1c, 0x01, 0xe9, 0x02, 0x78, 0x4b, 0x56, 0x93, 0xc6, 0x6f, 0xe1,
	0x78, 0x46, 0x5d, 0xc2, 0xda, 0xd6, 0x64, 0xb1, 0xb3, 0x13, 0xd8, 0xb9, 0x36, 0x75, 0x63, 0x82,
	0x4d, 0x73, 0x38, 0x51, 0xcd, 0x9e, 0x86, 0x19, 0x4b, 0x7a, 0x07, 0x48, 0x95, 0xad, 0x01, 0x75,
	0xdc, 0x85, 0x7f, 0x3f, 0x0a, 0xe8, 0x7d, 0x40, 0x56, 0x2b, 0x26, 0x22, 0x8e, 0x99, 0x88, 0x02,
	0x4e, 0xb0, 0xa4, 0x03, 0xb2, 0x64, 0xf5, 0xf0, 0xc5, 0x39, 0x14, 0x16, 0xfe, 0x9c, 0xae, 0x44,
	0xae, 0x95, 0x6f, 0xf3, 0xf2, 0xab, 0x74, 0xec, 0x01, 0x53, 0xf7, 0xe7, 0x14, 0x47, 0x5c, 0x69,
	0x08, 0xf5, 0x7f, 0x54, 0xf7, 0x4e, 0xc0, 0x1d, 0x9c, 0xe0, 0x39, 0x65, 0x91, 0x03, 0x7d, 0xc7,
	0x23, 0x98, 0x38, 0xee, 0x26, 0x76, 0x20, 0xc5, 0xdf, 0xb8, 0x84, 0x70, 0x19, 0x38, 0x1e, 0x41,
	0x22, 0x9c, 0xb0, 0x20, 0x99, 0xb3, 0x83, 0xe8, 0x3d, 0x40, 0x34, 0x72, 0x48, 0xbf, 0x10, 0x36,
	0x88, 0x97, 0x1b, 0xe9, 0x4e, 0xa3, 0xa4, 0x86, 0x33, 0x3c, 0xf4, 0x01, 0xf8, 0x08, 0x59, 0x0f,
	0x8b, 0xe5, 0x92, 0xb9, 0xc4, 0xcb, 0x2f, 0x0e, 0x9f, 0xb1, 0x22, 0xce, 0x32, 0xa5, 0x36, 0x40,
	0xda, 0x12, 0x55, 0x80, 0x7b, 0x62, 0x82, 0xaa, 0x98, 0x7b, 0x0a, 0xd1, 0x86, 0x29, 0xa8, 0x62,
	0x6e, 0x23, 0xbd, 0x06, 0x3e, 0xd3, 0x25, 0xdc, 0x80, 0x05, 0xf1, 0x06, 0x55, 0xbc, 0x83, 0xd2,
	0x45, 0xb2, 0x7c, 0xb4, 0xeb, 0x1b, 0x28, 0xce, 0xc3, 0x60, 0xe7, 0x50, 0x3d, 0x95, 0x95, 0x90,
	0x70, 0x4c, 0x91, 0xc6, 0x50, 0xde, 0xbb, 0xd2, 0x7c, 0xff, 0x4a, 0x31, 0x44, 0x32, 0x94, 0x66,
	0xd4, 0xf3, 0x1c, 0xdf, 0x0d, 0xcd, 0x08, 0xbb, 0x36, 0xd3, 0xae, 0xec, 0xb1, 0x1a, 0x95, 0x71,
	0xc2, 0x93, 0xbe, 0x73, 0x50, 0xc9, 0x96, 0x9e, 0x75, 0xfb, 0xff, 0xda, 0x70, 0x46, 0x21, 0x37,
	0xb2, 0x11, 0x0f, 0x27, 0xb7, 0xc6, 0x8d, 0x61, 0xde, 0x19, 0xc2, 0x11, 0x3a, 0x85, 0xf2, 0x95,
	0xa6, 0x60, 0xfb, 0xa3, 0xa6, 0xd8, 0xc2, 0x8f, 0x6d, 0x37, 0x4c, 0x24, 0x3f, 0x92, 0xf0, 0x73,
	0xdb, 0x45, 0x4d, 0x10, 0x06, 0xa6, 0xd2, 0xd3, 0x8d, 0xfe, 0x64, 0x84, 0xcd, 0x3e, 0xd6, 0x2c,
	0x4b, 0xf8, 0xb5, 0xed, 0x22, 0x01, 0xa0, 0xaf, 0x0c, 0xb5, 0x09, 0xd6, 0x94, 0xde, 0x58, 0xf8,
	0x9d, 0xc9, 0x5c, 0x62, 0x65, 0xa8, 0x09, 0x7f, 0xb6, 0xdd, 0xb3, 0xcf, 0x50, 0xdb, 0xff, 0x2b,
	0xc3, 0xe1, 0xd6, 0xad, 0xaa, 0x86, 0x4d, 0x8e, 0x10, 0x82, 0x1a, 0xab, 0x18, 0xa6, 0x3d, 0xd1,
	0x3e, 0xe9, 0x96, 0x2d, 0x70, 0xa8, 0x01, 0xc2, 0x68, 0xa0, 0x8c, 0x35, 0x9c, 0xc9, 0xe6, 0x50,
	0x1d, 0x4e, 0x6d, 0xf3, 0x46, 0x33, 0x32, 0xc9, 0xfc, 0xb4, 0xc8, 0x36, 0x3e, 0xff, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xae, 0xbe, 0x22, 0x82, 0xb2, 0x04, 0x00, 0x00,
}
