// Code generated by protoc-gen-go. DO NOT EDIT.
// source: newbee.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// --------------------------------------------------------------------------------
// 客户端发起的加入房间请求参数
type C2SJoinRoomReq struct {
	PlayerId             uint64   `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SJoinRoomReq) Reset()         { *m = C2SJoinRoomReq{} }
func (m *C2SJoinRoomReq) String() string { return proto.CompactTextString(m) }
func (*C2SJoinRoomReq) ProtoMessage()    {}
func (*C2SJoinRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{0}
}

func (m *C2SJoinRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SJoinRoomReq.Unmarshal(m, b)
}
func (m *C2SJoinRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SJoinRoomReq.Marshal(b, m, deterministic)
}
func (m *C2SJoinRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SJoinRoomReq.Merge(m, src)
}
func (m *C2SJoinRoomReq) XXX_Size() int {
	return xxx_messageInfo_C2SJoinRoomReq.Size(m)
}
func (m *C2SJoinRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SJoinRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_C2SJoinRoomReq proto.InternalMessageInfo

func (m *C2SJoinRoomReq) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *C2SJoinRoomReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 服务器端返回的加入房间请求结果
type S2CJoinRoomRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CJoinRoomRsp) Reset()         { *m = S2CJoinRoomRsp{} }
func (m *S2CJoinRoomRsp) String() string { return proto.CompactTextString(m) }
func (*S2CJoinRoomRsp) ProtoMessage()    {}
func (*S2CJoinRoomRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7594dbd1bcb6139, []int{1}
}

func (m *S2CJoinRoomRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CJoinRoomRsp.Unmarshal(m, b)
}
func (m *S2CJoinRoomRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CJoinRoomRsp.Marshal(b, m, deterministic)
}
func (m *S2CJoinRoomRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CJoinRoomRsp.Merge(m, src)
}
func (m *S2CJoinRoomRsp) XXX_Size() int {
	return xxx_messageInfo_S2CJoinRoomRsp.Size(m)
}
func (m *S2CJoinRoomRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CJoinRoomRsp.DiscardUnknown(m)
}

var xxx_messageInfo_S2CJoinRoomRsp proto.InternalMessageInfo

func (m *S2CJoinRoomRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*C2SJoinRoomReq)(nil), "protocol.C2SJoinRoomReq")
	proto.RegisterType((*S2CJoinRoomRsp)(nil), "protocol.S2CJoinRoomRsp")
}

func init() { proto.RegisterFile("newbee.proto", fileDescriptor_e7594dbd1bcb6139) }

var fileDescriptor_e7594dbd1bcb6139 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4b, 0x2d, 0x4f,
	0x4a, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a,
	0x4e, 0x5c, 0x7c, 0xce, 0x46, 0xc1, 0x5e, 0xf9, 0x99, 0x79, 0x41, 0xf9, 0xf9, 0xb9, 0x41, 0xa9,
	0x85, 0x42, 0x52, 0x5c, 0x1c, 0x05, 0x39, 0x89, 0x95, 0xa9, 0x45, 0x9e, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x2c, 0x41, 0x70, 0xbe, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x7e, 0x76, 0x6a, 0x9e, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0xa3, 0xa4, 0xc2, 0xc5, 0x17, 0x6c, 0xe4, 0x0c, 0x37,
	0xa3, 0xb8, 0x40, 0x48, 0x88, 0x8b, 0x25, 0x39, 0x3f, 0x25, 0x15, 0xac, 0x9f, 0x35, 0x08, 0xcc,
	0x4e, 0x62, 0x03, 0xdb, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xdd, 0x88, 0xe1, 0x8a,
	0x00, 0x00, 0x00,
}
